/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum10_1402023053;
import java.util.Random;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JFrame;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Rafli Dika
 */
public class OjekFTIFrame extends javax.swing.JFrame {
private Connection conn = null;
    /**
     * Creates new form OjekFTIFrame
     */
    public OjekFTIFrame() {
        initComponents();
        labelCaptcha.setText(generateCaptcha(7));
            buttonGroup1.add(radioButtonWanita);
                buttonGroup1.add(radioButtonPria);
    }
    
    static String generateCaptcha(int n){
        Random random = new Random(62);
            String chrs = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
                String captcha = "";
                while(n -->0){
                    int index = (int)(Math.random()*62);
                        captcha += chrs.charAt(index);
        }
        return captcha;
    }
    public void resetForm(){
        textFieldNamaDepan.setText("");
        textFieldNamaBelakang.setText("");
        buttonGroup1.clearSelection();
        comboBoxPengemudi.setSelectedItem("Pilih Jenis Pengemudi");
        checkBoxPersetujuan.setSelected(false);
        isiCaptcha.setText("");
        jLabel2.setText(generateCaptcha(7));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        titleDaftarSekarang = new javax.swing.JLabel();
        labelNamaDepan1 = new javax.swing.JLabel();
        textFieldNamaDepan = new javax.swing.JTextField();
        textFieldNamaBelakang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radioButtonPria = new javax.swing.JRadioButton();
        radioButtonWanita = new javax.swing.JRadioButton();
        comboBoxPengemudi = new javax.swing.JComboBox<>();
        checkBoxPersetujuan = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        labelCaptcha = new javax.swing.JLabel();
        labelMasukanCaptcha = new javax.swing.JLabel();
        isiCaptcha = new javax.swing.JTextField();
        buttonPendaftar = new javax.swing.JButton();
        buttonDaftarSekarang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        title2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Ojek Online FTI ");

        titleDaftarSekarang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleDaftarSekarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDaftarSekarang.setText("Daftar Sekarang !");

        labelNamaDepan1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNamaDepan1.setText("Nama Depan");

        textFieldNamaDepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaDepanActionPerformed(evt);
            }
        });

        jLabel1.setText("Jenis Kelamin");

        buttonGroup1.add(radioButtonPria);
        radioButtonPria.setText("Pria");
        radioButtonPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonPriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonWanita);
        radioButtonWanita.setText("Wanita");

        comboBoxPengemudi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Pengemudi", "Motor", "Mobik" }));

        checkBoxPersetujuan.setText("Saya menerima prasayarat ini");

        labelMasukanCaptcha.setText("Masukkan Captcha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMasukanCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelMasukanCaptcha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        buttonPendaftar.setText("Lihat Pendaftar!");
        buttonPendaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPendaftarActionPerformed(evt);
            }
        });

        buttonDaftarSekarang.setText("Daftar Sekarang!");
        buttonDaftarSekarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftarSekarangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Belakang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(titleDaftarSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNamaDepan1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(textFieldNamaDepan, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(radioButtonPria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioButtonWanita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxPengemudi, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkBoxPersetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonPendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(107, 107, 107)
                            .addComponent(buttonDaftarSekarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleDaftarSekarang)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaDepan1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNamaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonPria)
                    .addComponent(radioButtonWanita))
                .addGap(18, 18, 18)
                .addComponent(comboBoxPengemudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxPersetujuan)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPendaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDaftarSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonPriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonPriaActionPerformed

    private void textFieldNamaDepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaDepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaDepanActionPerformed

    private void buttonPendaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPendaftarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID", "Nama Depan", "Nama Belakang", "Jenis Kelamin", "Jenis Pengemudi"}, 0);
        JTable table = new JTable(tableModel);

        JPanel panel =   new JPanel();
        JScrollPane scrollPane = new JScrollPane(table);
        panel.add(scrollPane);

        jDialog1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jDialog1.setContentPane(panel);
        jDialog1.pack();
        jDialog1.setVisible(true);

        try{
            if(conn == null || conn.isClosed()){
                conn = Connect.getConnected();
            }

            Statement stmt = conn.createStatement();
            ResultSet resultSet = stmt.executeQuery("SELECT * FROM praktikum10");

            while(resultSet.next()){
                int id = resultSet.getInt("ID");
                String namaDepan = resultSet.getString("namaDepan");
                String namaBack = resultSet.getString("namaBack");
                String jenisKelamin = resultSet.getString("jenisKelamin");
                String kendaraan = resultSet.getString("kendaraan");

                tableModel.addRow(new Object[] {id, namaDepan, namaBack, jenisKelamin, kendaraan});
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_buttonPendaftarActionPerformed

    private void buttonDaftarSekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftarSekarangActionPerformed
        // TODO add your handling code here:
        if(textFieldNamaDepan.getText().isEmpty() && textFieldNamaBelakang.getText().isEmpty() && buttonGroup1.getSelection() == null && comboBoxPengemudi.getSelectedItem().toString().equals("Pilih Jenis Pengemudi") && !checkBoxPersetujuan.isSelected() && isiCaptcha.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu", "FORM KOSONG", JOptionPane.WARNING_MESSAGE);
}else{
            if(textFieldNamaDepan.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Nama depan harus terisi!", "NAMA DEPAN KOSONG", JOptionPane.WARNING_MESSAGE);
            }else{
                if(buttonGroup1.getSelection() == null){
                    JOptionPane.showMessageDialog(this, "Mohon pilih jenis kelamin terlebih dahulu!", "JENIS KELAMIN TIDAK DIPILIH", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(isiCaptcha.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Mohon isi captcha terlebih dahulu!", "CAPTCHA KOSONG", JOptionPane.WARNING_MESSAGE);
                    }else{
                        if(labelCaptcha.getText().equals(isiCaptcha.getText())){
                            if(checkBoxPersetujuan.isSelected()){
                                if(!"Pilih Jenis Pengemudi".equals(comboBoxPengemudi.getSelectedItem().toString())){
                                    try{
                                        if(conn == null || conn.isClosed()){
                                            conn = Connect.getConnected();
                                        }

                                        String query = "INSERT INTO praktikum10 (namaDepan, namaBack, jenisKelamin, kendaraan) values (?, ?, ?, ?)";

                                        try(PreparedStatement ps = conn.prepareStatement(query)){
                                            ps.setString(1, textFieldNamaDepan.getText());
                                            ps.setString(2, textFieldNamaBelakang.getText());
                                            ps.setString(3, buttonGroup1.getSelection().isSelected() ? "Pria" : "Wanita");
                                            ps.setString(4, comboBoxPengemudi.getSelectedItem().toString());
                                            ps.executeUpdate();
                                        }
                                        JOptionPane.showMessageDialog(this, "Registration Success!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                                        resetForm();
                                    }catch(SQLException ex){
                                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(this, "Mohon pilih jenis pengemudi terlebih dahulu!", "JENIS PENGEMUDI TIDAK DIPILIH", JOptionPane.WARNING_MESSAGE);
                                }
                            }else{
                                JOptionPane.showMessageDialog(this, "Kotak persetujuan harus dicentang!", "KOTAK PERSETUJUAN KOSONG", JOptionPane.WARNING_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "Captcha tidak sesuai!", "CAPTCHA SALAH", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_buttonDaftarSekarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OjekFTIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OjekFTIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OjekFTIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OjekFTIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OjekFTIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDaftarSekarang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonPendaftar;
    private javax.swing.JCheckBox checkBoxPersetujuan;
    private javax.swing.JComboBox<String> comboBoxPengemudi;
    private javax.swing.JTextField isiCaptcha;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCaptcha;
    private javax.swing.JLabel labelMasukanCaptcha;
    private javax.swing.JLabel labelNamaDepan1;
    private javax.swing.JRadioButton radioButtonPria;
    private javax.swing.JRadioButton radioButtonWanita;
    private javax.swing.JTextField textFieldNamaBelakang;
    private javax.swing.JTextField textFieldNamaDepan;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel titleDaftarSekarang;
    // End of variables declaration//GEN-END:variables
}
